### ISSUE TITLE
Tests do not run correctly.

### ISSUE THREAD

**Issue by Lozov-Petr** [jscert/jscert#15]
After fix of issue #14 commands `make init` and `make` performed correctly.
But when I try to start tests using `./runtests.py --verbose` I get for every test
```
/home/not-kill/git/jscert/tests/test262/ch08/8.4/S8.4_A5.js
Aborted...

Fatal error: exception Parser.ParserFailure("Could not find parser at interp/parser/lib/js_parser.jar/js_parser.jar (No such file or directory)")
```
I tried to correct path to `js_parser.jar` in `runtests.py`
```diff
-os.path.join("interp","parser","lib","js_parser.jar")
+os.path.join("..","..",".opam","4.02.3","lib","JS_Parser","runtime")
```
In this case I get for every test
```
/home/not-kill/git/jscert/tests/test262/ch08/8.4/S8.4_A5.js
Failed :/

Parsing problem with the file `XML File not found: /home/not-kill/git/jscert/tests/test262/ch08/8.4/S8.4_A5.xml'.
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/javascript/rhino/head/EvaluatorException
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:56)
Caused by: java.lang.ClassNotFoundException: com.google.javascript.rhino.head.EvaluatorException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
	... 3 more
```

Could you check and fix JSRef interpreter and JS parser integration?
@Mbodin

**Comment by Lozov-Petr** [comment]
Oh, I realized what the problem was.
I used newer java version than `jssert` expect.
When I switch java version to `java-8`, tests performed correctly.

**Comment by Lozov-Petr** [comment]
After ``./runtests.py `cat ./test_data/interesting_tests.txt` --verbose`` performing with `java-8` for `interesting_tests.txt` only I have got follow response:

```
The following tests failed:
/home/not-kill/git/jscert/tests/test262/ch15/15.2/15.2.3/15.2.3.8/15.2.3.8-2-c-1.js
/home/not-kill/git/jscert/tests/test262/ch15/15.2/15.2.3/15.2.3.8/15.2.3.8-2-a-7.js
/home/not-kill/git/jscert/tests/test262/ch15/15.2/15.2.3/15.2.3.9/15.2.3.9-2-a-9.js
/home/not-kill/git/jscert/tests/test262/ch15/15.2/15.2.3/15.2.3.9/15.2.3.9-2-d-1.js
/home/not-kill/git/jscert/tests/test262/ch10/10.2/10.2.1/S10.2.1_A2.js
/home/not-kill/git/jscert/tests/test262/ch10/10.2/10.2.1/S10.2.1_A3.js
/home/not-kill/git/jscert/tests/test262/ch13/13.1/13.1-1-2.js
/home/not-kill/git/jscert/tests/test262/ch13/13.1/13.1-1-1.js
The following tests were abandoned
/home/not-kill/git/jscert/tests/test262/ch11/11.10/11.10.2/S11.10.2_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.10/11.10.3/S11.10.3_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.10/11.10.1/S11.10.1_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.4/11.4.4/S11.4.4_A3_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.4/11.4.4/S11.4.4_A4_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.4/11.4.5/S11.4.5_A3_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.4/11.4.5/S11.4.5_A4_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.4/11.4.7/S11.4.7_A3_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.4/11.4.8/S11.4.8_A3_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.4/11.4.6/S11.4.6_A3_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.5/11.5.1/S11.5.1_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.5/11.5.3/S11.5.3_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.5/11.5.2/S11.5.2_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.3/11.3.1/S11.3.1_A4_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.3/11.3.1/S11.3.1_A3_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.3/11.3.2/S11.3.2_A3_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.3/11.3.2/S11.3.2_A4_T5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.7/11.7.3/S11.7.3_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.7/11.7.1/S11.7.1_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.7/11.7.2/S11.7.2_A3_T1.5.js
/home/not-kill/git/jscert/tests/test262/ch11/11.6/11.6.2/S11.6.2_A3_T1.5.js
There were 2200 passes, 8  fails, and 21 abandoned.
```
Could you please validate if this response is correct?
If the response isn't incorrect, could you update the project to Java 8? Or update the instructions for installing Java 6?
@Mbodin
